# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
- repo: local
  hooks:
  - id: gradle-lint
    name: Run Kotlin linters
    description: This hook runs Gradle to execute linters
    language: system
    entry: docker compose --profile dev run -T --rm linter
    types: [kotlin]
    pass_filenames: false
